Riftware 4.2.1

diff --git a/scripts/vm_image/mkvmimg b/scripts/vm_image/mkvmimg
--- a/scripts/vm_image/mkvmimg
+++ b/scripts/vm_image/mkvmimg
@@ -47,7 +47,7 @@ die() {
 }
 
 announce() {
-	echo -e "=============================\n$*\n===========================" >&2
+	echo -e "=============================\n$*\n=============================" >&2
 }
 
 fetch_seed() {
@@ -104,6 +104,8 @@ setup() {
 		die "Failed to find free nbd node"
 	fi
 
+	echo "nbd_dev=${nbd_dev}"
+
 	qemu-nbd -c ${nbd_dev} ${SEED_PATH}\
 		|| die "Failed to qemu-nbd ${SEED_PATH} on ${nbd_dev}"
 	_NBD_NODES="${_NBD_NODES} ${nbd_dev}"
@@ -128,6 +130,8 @@ setup() {
 	if [ ${rc} -ne 0 ]; then
 		die "Failed to sync to ${STAGING}"
 	fi
+
+	echo "Done syncing to ${STAGING}"
 
 	for mp in sys proc dev; do
 		mount -o bind /${mp} ${STAGING}/${mp} || die "Failed to bind mount ${mp}"
@@ -179,8 +183,8 @@ pack_qcow2() {
 	img_size=$((img_size + ${_EXTRA_DISK_SPACE_K} + 500 * 1024))
 
 	dest=${IMG_PREFIX}.qcow2
-	echo ${sha} >${STAGING}/etc/rift.hash
 
+	echo "Setting up NBD:"
 	qemu-img create -f qcow2 ${dest} ${img_size}k
 	nbd_dev=$(_find_free_nbd_node)
 
@@ -191,6 +195,7 @@ pack_qcow2() {
 	qemu-nbd -c ${nbd_dev} ${dest} || die "Failed to qemu-nbd ${dest} on ${nbd_dev}"
 	_NBD_NODES="${_NBD_NODES} ${nbd_dev}"
 
+	echo "Partitioning and Formatting:"
 	echo ",," | sfdisk ${nbd_dev} || die "Failed to partition ${nbd_dev}"
 	kpartx -s -a ${nbd_dev} || die "kpartx ${nbd_dev} failed"
 	p_dev=/dev/mapper/${nbd_dev##*/}p1
@@ -202,13 +207,25 @@ pack_qcow2() {
 		die "Filed to mount ${dest} on ${tmp_mp}"
 	fi
 
+	#echo "PQ1) Checking"
+	#ls -all ${STAGING}/home/rift/scripts/
+	#ls -all ${tmp_mp}/home/rift/scripts/
+
+	echo "Start Rsyncing..."
 	rsync -a --exclude='/sys/*' --exclude='/proc/*' ${STAGING}/ ${tmp_mp}/
 	rc=$?
 	if [ ${rc} -ne 0 ]; then
 		umount -f ${tmp_mp}
 		die "Failed to sync from ${STAGING}"
 	fi
+	echo "Done Rsyncing."
 
+	echo "PQ2) Checking Scripts"
+	#ls -all ${STAGING}/home/rift/scripts/*
+	ls -all ${tmp_mp}/home/rift/scripts/*
+
+	# I think this assumes the host is running the right release
+	#
 	for bind_mp in dev proc sys; do
 		mount -o bind /${bind_mp} ${tmp_mp}/${bind_mp} || die "Failed to bind mount ${tmp_mp}/${bind_mp}"
 		_MOUNTS="${_MOUNTS} ${tmp_mp}/${bind_mp}"
@@ -216,8 +233,7 @@ pack_qcow2() {
 
 	# grub2 install isonly really needed for qcow2/kvm -- AWS uses grub
 
-	set -x
-	chroot ${tmp_mp} yum install -y grub2 || die "Failed to yum install grub2"
+	chroot ${tmp_mp} $YUM install -y grub2 || die "Failed to yum install grub2"
 	chroot ${tmp_mp} grub2-mkconfig -o /boot/grub2/grub.cfg || die "Failed to create grub2 config"
 	chroot ${tmp_mp} grub2-set-default "Fedora, with Linux ${KERNEL_REV}"
 
@@ -225,7 +241,11 @@ pack_qcow2() {
 		(hd0) ${nbd_dev}
 	EOF
 
-	chroot ${tmp_mp} grub2-install -f ${nbd_dev} || "Failed to grub2-install"
+	if [ $RELEASE == 20 ]; then
+		chroot ${tmp_mp} grub2-install -f ${nbd_dev} || die "Failed to grub2-install"
+	else
+		chroot ${tmp_mp} grub2-install ${nbd_dev} || die "Failed to grub2-install"
+	fi
 
 	cat > ${tmp_mp}/etc/fstab <<-EOF
 		/dev/vda1 / ext4    defaults,noatime 0 0
@@ -245,7 +265,7 @@ if lspci | grep -q "Co-processor: Intel Corporation Device 0443" ; then
    echo "Leave qat-service running"
    chkconfig qat_service on
    service qat_service start
-else 
+else
    echo "Disable qat-service running"
    chkconfig qat_service off
    service qat_service stop
@@ -297,15 +317,17 @@ pack_image() {
 
 	# NOTE this menu is for grub which is used for AWS
 	# kvm uses grub2 
-	cat > ${tmp_mp}/boot/grub/menu.lst <<-EOF
-		default=0
-		timeout=0
+	if [ -n "$KERNEL_REV" ]; then
+		cat > ${tmp_mp}/boot/grub/menu.lst <<-EOF
+			default=0
+			timeout=0
 
-		title Fedora ($KERNEL_REV})
-			root (hd0)
-			kernel /boot/vmlinuz-${KERNEL_REV} ro root=/dev/xvda1 console=hvc0 console=ttyS0,115200n8 LANG=en_US.UTF-8 
-			initrd /boot/initramfs-${KERNEL_REV}.img
-	EOF
+			title Fedora ($KERNEL_REV})
+				root (hd0)
+				kernel /boot/vmlinuz-${KERNEL_REV} ro root=/dev/xvda1 console=hvc0 console=ttyS0,115200n8 LANG=en_US.UTF-8 
+				initrd /boot/initramfs-${KERNEL_REV}.img
+		EOF
+	fi
 
 	cat > ${tmp_mp}/etc/fstab <<-EOF
 		/dev/xvda1 / ext4    defaults,noatime 0 0
@@ -321,7 +343,7 @@ pack_image() {
 }
 
 cmd() {
-	echo "${@:0:40} ..." >&2
+	echo "${@:1:40} ..." >&2
 	if [ "${STAGING}" == "" ]; then
 			/bin/bash -c "$*" || die "Failed to run $@"
 	else
@@ -332,7 +354,7 @@ cmd() {
 }
 
 yum_install() {
-	cmd /bin/yum --assumeyes --nogpgcheck install "$@" || die "yum '$@' failed"
+	cmd $YUM --assumeyes --nogpgcheck install "$@" || die "yum '$@' failed"
 }
 
 
@@ -341,42 +363,78 @@ pip_install() {
 	repo=$2
 	shift
 	shift
-	cmd $cmd install --use-wheel --no-index \
-		--find-links=https://wheel.riftio.com/mirrors/${repo}/ "$@" || die "$cmd install $@ from $repo failed"
+	if [ $USE_INTERNET_REPOS == 1 ]; then
+		cmd $cmd install "$@" || die "$cmd install $@ from internet failed"
+	else
+		#cmd $cmd install --use-wheel --no-index \
+		#	--find-links=https://wheel.riftio.com/mirrors/${repo}/ \
+		#	"$@" || die "$cmd install $@ from $repo failed"
+		cmd $cmd install --use-wheel --no-index \
+			--find-links=${repo} \
+			"$@" || die "$cmd install $@ from $repo failed"
+	fi
 }
 
-pip2_install() { 
-	pip_install /bin/pip2 wheelhouse "$@"
+pip2_install() {
+	#pip_install /bin/pip2 wheelhouse "$@"
+	# pip2 needs to be non-ssl for now
+	pip_install /bin/pip2 http://wheel.riftio.com/mirrors/wheelhouse/ "$@"
 }
 
 pip3_install() {
-	pip_install /bin/python3-pip python3_wheelhouse "$@"
+	#pip_install $PIP3_INSTALLER python3_wheelhouse "$@"
+	pip_install $PIP3_INSTALLER https://wheel.riftio.com/mirrors/python3_wheelhouse/ "$@"
 }
 
 pip3_install_kilo_modules() {
-	pip_install /bin/python3-pip python3_kilo_wheelhouse "$@"
+	#pip_install $PIP3_INSTALLER python3_kilo_wheelhouse "$@"
+	pip_install $PIP3_INSTALLER https://wheel.riftio.com/mirrors/python3_kilo_wheelhouse/ "$@"
 }
+
+pip3_install_kilo42_modules() {
+	#pip_install $PIP3_INSTALLER python3_kilo_wheelhouse "$@"
+	pip_install $PIP3_INSTALLER https://wheel.riftio.com/mirrors/python3_kilo_rel_4.2_wheelhouse/ "$@"
+}
+
 
 setup_fedora_repos() {
 	announce $FUNCNAME
-	cmd yum clean all
-	rm -f $STAGING/etc/yum.repos.d/*
-	cmd  rpm --rebuilddb
-	cmd yum localinstall --assumeyes http://repo.riftio.com/releases/riftware-release-latest.rpm
 
-	cmd yum clean all
-	cmd yum makecache
+	if [ $ONLY_RIFT_REPOS == 1 ]; then
+		cmd $YUM clean all
+		rm -f $STAGING/etc/yum.repos.d/*
+		cmd  rpm --rebuilddb
+	fi
+	if [[ $REPO_FILE =~ .rpm$ ]]; then
+		cmd $YUM localinstall --assumeyes $REPO_FILE
+	else
+		cp $REPO_FILE $STAGING/etc/yum.repos.d/
+	fi
 
-	yum_install python3 python3-pip
-	cat  $STAGING/bin/python3-pip
-	ls -ld $STAGING/bin/*pip*
-	# the default version of pip is so old that it can't use a https server that has multiple servers
-    cmd curl https://wheel.riftio.com/mirrors/python3_wheelhouse/pip-7.1.2-py2.py3-none-any.whl -o pip-7.1.2-py2.py3-none-any.whl
-    cmd /bin/python3-pip install pip-7.1.2-py2.py3-none-any.whl 
+	cmd $YUM clean all
+	cmd $YUM makecache
 
-	perl -i -p -e 's/1\.4\.[0-9]/7.1.2/g;' $STAGING/bin/python3-pip
+	if [ $FIX_PIP == 1 ]; then
+
+		# PIP3
+		echo "1) pip3 version is: "`cmd /bin/python3-pip --version`
+		rm -Rfv /tmp/pip_build_root # fixes: The temporary folder for building (/tmp/pip_build_root) is not owned by your user!
+		yum_install python3 python3-pip
+		#cat  $STAGING/bin/python3-pip
+		ls -ld $STAGING/bin/*pip*
+		# the default version of pip is so old that it can't use a https server that has multiple servers
+		echo "2) pip3 version is: "`cmd /bin/python3-pip --version`
+	    	cmd curl https://wheel.riftio.com/mirrors/python3_wheelhouse/pip-7.1.2-py2.py3-none-any.whl -o /tmp/pip-7.1.2-py2.py3-none-any.whl
+    		cmd /bin/python3-pip install /tmp/pip-7.1.2-py2.py3-none-any.whl
+		perl -i -p -e 's/1\.4\.[0-9]/7.1.2/g;' $STAGING/bin/python3-pip
+		echo "3) pip3 version is: "`cmd /bin/python3-pip --version`
+
+	else
+		pip3 install --upgrade pip
+	fi
 
 	yum_install yum-utils
+	# ok if this fails
 	cmd yum-config-manager --quiet --enable updates3
 }
 
@@ -387,19 +445,21 @@ config_rw_repos() {
 	# release(stable) is the default in the riftware.repo
 	# we never want to leave these enabled in production
 	if [[ "$RW_REPO" = "nightly" ]]; then
-		YUM_OPTS="--enablerepo=RIFT.ware-nightly,RIFT.ware-testing"
+		YUM_OPTS="--enablerepo=RIFT.ware-4.1-nightly,RIFT.ware-4.1-testing"
 	elif [[ "$RW_REPO" = "testing" ]]; then
-		YUM_OPTS="--enablerepo=RIFT.ware-testing"
+		YUM_OPTS="--enablerepo=RIFT.ware-4.1-testing"
 	fi
 
-	cmd yum clean all
-	cmd yum makecache
+	cmd $YUM clean all
+	cmd $YUM makecache
 
 }
 
 install_kernel() {
 
-	yum_install kernel-${KERNEL_REV} kernel-devel-${KERNEL_REV} kernel-modules-extra-${KERNEL_REV}
+	if [ -n "$KERNEL_REV" ]; then
+		yum_install kernel-${KERNEL_REV} kernel-devel-${KERNEL_REV} kernel-modules-extra-${KERNEL_REV}
+	fi
 
 }
 
@@ -414,10 +474,15 @@ setup_usr_rift() {
 	cmd adduser -m -s /bin/bash -U rift
 	echo "rift:rift" | cmd chpasswd
 
-	rm -rf $STAGING/home/rift/scripts
+	#rm -rf $STAGING/home/rift/scripts
 	#ln -s /usr/rift/scripts $STAGING/home/rift/scripts
+
 	yum_install $YUM_OPTS riftware-base
 
+	#
+	# FIX ME
+	#cp $REPO_FILE $STAGING/etc/yum.repos.d/
+	# this looks fixed in setup_fedora_repos
 
 }
 
@@ -439,6 +504,23 @@ setup_access() {
 
 }
 
+# this adds Rift data into the image, such as the git hash, modes, version, etc.
+brand_images() {
+
+        announce $FUNCNAME
+
+	echo "${SHA}" > ${STAGING}/etc/rift.hash
+	echo -e "checking /etc/rift.hash: `cat ${STAGING}/etc/rift.hash` ";
+
+	# remove extra spaces and make into CSV
+	clean_modes=$(echo "$MODES" | awk '$1=$1' | sed 's/ /,/g' )
+
+	json=$(echo "{\"modes\":\"${clean_modes}\",\"build_number\":\"${RIFT_BUILD_NUMBER}\",\"version\":\"${VERSION}\",\"branch\":\"${BRANCH}\",\"hash\":\"${SHA}\"}")
+	echo "${json}" > ${STAGING}/etc/rift.vm
+        echo -e "checking /etc/rift.vm: `cat ${STAGING}/etc/rift.vm` ";
+
+
+}
 
 output_images() {
 	local output_type
@@ -495,6 +577,14 @@ _NBD_NODES=""
 _EXTRA_DISK_SPACE_K=1572864
 KERNEL_REV="3.12.9-301.fc20.x86_64"
 
+REPO_FILE=http://repo.riftio.com/releases/riftware-release-latest.rpm
+ONLY_RIFT_REPOS=1
+USE_INTERNET_REPOS=0
+FIX_PIP=1
+PIP3_INSTALLER=/bin/python3-pip
+YUM=/bin/yum
+RELEASE=20
+
 usage() {
 	MODES=$(ls $(dirname $0).rpm)
 	cat <<-EOF
@@ -516,6 +606,8 @@ usage() {
 			--install-only           Only install packages, do not produce images
 			-m, --modes [MODES]      Include packages for specified modes
 			-e, --extra              extra space to reserve in GB
+			--repo_file file         file to use to enable additional repos
+			--internet               do not delete existing repo files and get stuff from internet
 
 		OUTPUTS:
 			qcow2:         Openstack/kvm suitable image
@@ -575,6 +667,33 @@ while [ $# -gt 0 ]; do
 		--clean|-c)
 			CLEAN_FIRST=true
 			;;
+		--repo-file)
+			shift
+			REPO_FILE="$1"
+			;;
+		--internet)
+			ONLY_RIFT_REPOS=0
+			USE_INTERNET_REPOS=1
+			;;
+		--no-fix-pip)
+			FIX_PIP=0
+			;;
+		--kernel)
+			shift
+			KERNEL_REV="$1"
+			;;
+		--fc23)
+			# short hand
+			PIP3_INSTALLER=/bin/pip3
+			FIX_PIP=0
+			ONLY_RIFT_REPOS=0
+			USE_INTERNET_REPOS=1
+			KERNEL_REV=""
+			SEED="Fedora-Cloud-Base-23-20151030.x86_64.qcow2"
+			YUM=dnf
+			RELEASE=23
+			REPO_FILE="riftware-release.repo"
+			;;
 		*)
 			set -x
 			echo "args= $# "
@@ -618,14 +737,32 @@ for mode in $modes_in; do
 	add_mode $mode
 done
 
-sha=$(git rev-parse --short HEAD)
-if [ -z "${sha}" ]; then
+SHA=$(git rev-parse --short HEAD)
+if [ -z "${SHA}" ]; then
 	die "Failed to find a git sha"
 fi
-IMG_PREFIX="${IMG_PREFIX}-${sha}"
 
+BRANCH=$(git rev-parse --abbrev-ref HEAD)
+VERSION=$(cat ./RELEASE) # full 4 digits like 4.2.0.0
+
+RIFT_ROOT=$(pwd)
+source ./scripts/packaging/getbuild
+echo "RIFT_BUILD_NUMBER=${RIFT_BUILD_NUMBER}";
+
+
+#if [ $BRANCH == "master" ]; then
+#	IMG_PREFIX="${IMG_PREFIX}-${SHA}"
+#else
+	#IMG_PREFIX="${IMG_PREFIX}-${VERSION}-${BRANCH}-${SHA}"
+	#IMG_PREFIX="${IMG_PREFIX}-${VERSION}-${RIFT_BUILD_NUMBER}-${BRANCH}"
+#fi
+
+IMG_PREFIX="${IMG_PREFIX}-${VERSION}-${RIFT_BUILD_NUMBER}-${BRANCH}"
 
 announce "BUILDING $IMG_PREFIX "
+echo "MODES=$MODES "
+#echo "printenv:"
+#printenv
 
 
 #check_build_area  -- we cannot be under $RIFT_ROOT unless we are also in .build
@@ -657,22 +794,36 @@ for mode in $MODES; do
 	announce "installing $mode"
 	basename="$VM_DIR/$mode"
 	if [ -s $basename.setup.sh ]; then
+		announce "Sourcing $basename.setup.sh"
 		source $basename.setup.sh
 		cmd df -h /
 	fi
 	if [ -s $basename.rpms ]; then
+		announce "Installing $basename.rpms"
 		yum_install $(cat $basename.rpms)
 		cmd df -h /
 	fi
+	if [ -s $basename.pip ]; then
+		announce "Installing $basename.pip"
+		pip2_install $(cat $basename.pip)
+		cmd df -h /
+	fi
 	if [ -s $basename.pip3 ]; then
+		announce "Installing $basename.pip3"
 		pip3_install $(cat $basename.pip3)
 		cmd df -h /
 	fi
 	if [ -s $basename.kilo ]; then
-		pip3_install_kilo_modules $(cat $basename.kilo)
+		announce "Installing $basename.kilo"
+
+		#pip3_install_kilo_modules $(cat $basename.kilo)
+		# switch to new kilo pip3 wheelhouse after 4.1
+		pip3_install_kilo42_modules $(cat $basename.kilo)
+
 		cmd df -h /
 	fi
 	if [ -s $basename.config.sh ]; then
+		announce "Sourcing $basename.config.sh"
 		source $basename.config.sh
 		cmd df -h /
 	fi
@@ -688,6 +839,7 @@ if ${INSTALL_ONLY}; then
 	exit 0
 fi
 
+brand_images
 output_images
 
 _on_exit
